### ISSUE TITLE
what's the slot-token

### ISSUE THREAD

**Issue by chenxizhang** [Stuyk/honkit-plugin-adsense#1]
Hi how to set the slot-token?

**Comment by Stuyk** [comment]
Sorry plugin is a bit old; I can't even remember anymore at this point. Here's a screenshot from an old repository with the data I was using at the time.

![](https://i.imgur.com/iMhjust.png)

**Comment by Stuyk** [comment]
I think it may be based on old adsense tokens; so probably needs to be updated but I'd rather push for something on `vitepress` than `vuepress`.

**Comment by chenxizhang** [comment]
> I think it may be based on old adsense tokens; so probably needs to be updated but I'd rather push for something on `vitepress` than `vuepress`.

Thanks so much, @Stuyk  You did great job, looking forward to the update
